### ISSUE TITLE
zoom in ,out not working with font style

### ISSUE THREAD

**Issue by altaf2892** [agilie/RotatableAutofitEditText#1]
**zoom in ,out not working with font style**

**for example** ` editText.setTypeface(Utility.GetBLACKJAR(getApplicationContext()));`

> if i settext to edittext with styled font zoom in and out wont work ,zoom in and out only works with normal font style

**Comment by akotsuba** [comment]
@altaf2892 Hi! Yes, you're right, we'll try to fix it soon. Thanks for the feedback!

**Comment by altaf2892** [comment]
ok...   your welcome.... fix it soon
